name: Deploy Web App

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'apps/infra/src/deployments/web.ts'
      - 'apps/infra/src/deployments/shared.ts'
      - 'packages/**'
    secrets:
      SENTRY_ORG:
        required: true
      SENTRY_PROJECT:
        required: true
      SENTRY_DSN:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deployment:
    uses: ./.github/workflows/deploy-common.yml
    with:
      working-directory: apps/infra
      stack-name: web-production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARN_OF_IAM_ROLE_TO_ASSUME: ${{ secrets.ARN_OF_IAM_ROLE_TO_ASSUME }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
