name: Linter & Types

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      workflow_call:
        type: boolean
        required: false
        default: false

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Use Turbo to build affected packages
        run: pnpm turbo build --cache-dir=.turbo --filter="./packages/**"

      - name: Prettier
        run: pnpm prettier:check

      - name: Lint
        run: pnpm lint

      - name: TypeScript
        run: pnpm tc --cache-dir=.turbo
